import turtle
screen = turtle.Screen()
screen.bgcolor("black")
a = turtle.Turtle()
a.shape("turtle")
def circle(pen,fill,r1):
  a.pencolor(pen)
  a.fillcolor(fill)
  a.begin_fill()
  a.circle(r1)
  a.end_fill()
circle("red","red",150)
a.penup()
a.left(49)
a.forward(115)
a.pendown()
circle("blue","blue",100)
a.penup()
a.left(58)
a.forward(80)
a.pendown()
circle("yellow","yellow",50)
a.ht()
