import turtle
screen = turtle.Screen()
a = turtle.Turtle()
a.shape("turtle")
screen.bgcolor("light pink")
b = input("enter your name")
a.pencolor("blue")
a.right(70)
a.forward(100)
a.right(70)
a.forward(100)
a.right(70)
a.forward(100)
a.right(70)
a.forward(100)
a.right(70)
a.forward(100)
